[package]
name = "unix_mode"
version = "0.1.0"
authors = ["Martin Pool <mbp@google.com>"]
edition = "2018"
description = "Decode Unix file mode bits (even on non-Unix platforms)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
