[package]
name = "rsyn"
version = "0.0.0"
authors = ["Martin Pool <mbp@google.com>"]
edition = "2018"
description = "[placeholder] Wire-compatible rsync client"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sourcefrog/rsyn"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
