name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Install rsync from Chocolatey
      if: ${{ matrix.os == 'windows-latest' }}
      run: choco install rsync
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all --verbose
    - name: Test
      run: cargo test --verbose
      env:
        RUST_BACKTRACE: 1
